// Copyright 2026 openhands and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCatalogCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "catalog",
		Short:       "Browse the Printify catalog including blueprints, print providers, product variants, and shipping information.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCatalogRetrieveAlistOfAllPrintProvidersThatFulfillOrdersForAspecificBlueprintCmd(flags))
	cmd.AddCommand(newCatalogRetrieveAlistOfAvailablePrintProvidersCmd(flags))
	cmd.AddCommand(newCatalogRetrieveAlistOfVariantsOfAblueprintFromAspecificPrintProviderCmd(flags))
	cmd.AddCommand(newCatalogRetrieveAspecificBlueprintCmd(flags))
	cmd.AddCommand(newCatalogRetrieveAspecificPrintProviderCmd(flags))
	cmd.AddCommand(newCatalogRetrieveAvailableShippingListInformationCmd(flags))
	cmd.AddCommand(newCatalogRetrieveEconomyShippingMethodInformationCmd(flags))
	cmd.AddCommand(newCatalogRetrieveExpressShippingMethodInformationCmd(flags))
	cmd.AddCommand(newCatalogRetrievePriorityShippingMethodInformationCmd(flags))
	cmd.AddCommand(newCatalogRetrieveShippingInformationCmd(flags))
	cmd.AddCommand(newCatalogRetrieveSpecificShippingMethodInformationCmd(flags))
	cmd.AddCommand(newCatalogRetrievesListOfBlueprintsInTheCmd(flags))
	return cmd
}
