// Copyright 2026 openhands and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newShopsOrdersJsonRetrieveAlistOfOrdersCmd(flags *rootFlags) *cobra.Command {
	var flagLimit string
	var flagPage string
	var flagStatus string
	var flagSku string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "retrieve-alist-of-orders <shop_id>",
		Aliases:     []string{"get"},
		Short:       "Retrieve a list of orders",
		Example:     "  printify2-pp-cli shops orders-json retrieve-alist-of-orders 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "orders-json.retrieve-alist-of-orders", "pp:method": "GET", "pp:path": "/v1/shops/{shop_id}/orders.json", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <shop_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <shop_id>"))
			}
			path := "/v1/shops/{shop_id}/orders.json"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("shop_id is required\nUsage: %s <%s>", cmd.CommandPath(), "shop_id"))
			}
			path = replacePathParam(path, "shop_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "live", "orders-json", path, map[string]string{
				"limit":  formatCLIParamValue(flagLimit),
				"page":   formatCLIParamValue(flagPage),
				"status": formatCLIParamValue(flagStatus),
				"sku":    formatCLIParamValue(flagSku),
			}, nil, flagAll, "page", "page", "limit", 100, "", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			outputData := collectionItemsForOutput(data, path)
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(outputData, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagLimit, "limit", "", "Results per page (default: 10, maximum: 10)")
	cmd.Flags().StringVar(&flagPage, "page", "", "Paginate through list of results")
	cmd.Flags().StringVar(&flagStatus, "status", "", "Filter results by order status")
	cmd.Flags().StringVar(&flagSku, "sku", "", "Filter results by product SKU - response will contain only those orders that have at least one product with passed SKU")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
