// Copyright 2026 openhands and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newShopsOrdersJsonCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "orders-json",
		Short:       "Get and submit orders json for shops",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newShopsOrdersJsonRetrieveAlistOfOrdersCmd(flags))
	cmd.AddCommand(newShopsOrdersJsonSubmitAnOrderCmd(flags))
	return cmd
}
