// Copyright 2026 openhands and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUploadsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "uploads",
		Short:       "Upload and manage images and assets.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newUploadsAnImageCmd(flags))
	cmd.AddCommand(newUploadsRetrieveAnUploadedImageByIdCmd(flags))
	cmd.AddCommand(newUploadsArchiveJsonCmd(flags))
	return cmd
}
